#!/bin/sh
#
# Start linux Weston...
#

# Load default env variables from profiles(e.g. /etc/profile.d/weston.sh)
. /etc/profile

case "$1" in
  start)
		printf "Starting Weston: "
		export LC_ALL='zh_CN.utf8'

		# Uncomment to disable mirror mode
		# unset WESTON_DRM_MIRROR

		export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/var/run}
		export QT_QPA_PLATFORM=${QT_QPA_PLATFORM:-wayland}

		weston --tty=2 --idle-time=0 --log=/var/log/weston.log --warm-up &
	;;
  stop)
		killall weston
		printf "stop finished"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
