#! /bin/sh

case "$1" in
    start)
		adduser forlinx << EOF
forlinx
forlinx

EOF

adduser ftp << EOF
ftp
ftp

EOF
		
		rm /etc/init.d/S98user
		sync
        ;;
    stop)
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

