#! /bin/sh

case "$1" in
    start)
		adduser jw3568 << EOF
jw3568
jw3568

EOF

		rm /etc/init.d/S98user
		sync
        ;;
    stop)
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

